spring:
    application:
        name: sbhm
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Kofax123!
        url: jdbc:mysql://localhost:3306/sbhm
        username: root
    jpa:
        hibernate:
            ddl-auto: update
    liquibase:
        change-log: classpath:/db/changelog/app-changelog.xml
        default-schema: sbhm
